/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeButton: typeof import('./src/components/change-button.vue')['default']
    Colorcanvas: typeof import('./src/components/colorcanvas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Function1: typeof import('./src/components/function1.vue')['default']
    Function3: typeof import('./src/components/function3.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    'Login+heart': typeof import('./src/components/login+heart.vue')['default']
    Mapboxgl: typeof import('./src/components/Mapboxgl.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Mobilenav: typeof import('./src/components/Mobilenav.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RealTimeMoni: typeof import('./src/components/Real-timeMoni.vue')['default']
    RLmoniMobile: typeof import('./src/components/RLmoni-mobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Run_python: typeof import('./src/components/run_python.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
  }
}
